# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(name: 'Ken Harsch', nickname: 'Ken', email:'kharsch@brandeis.edu', password: 'swlipds12', admin: 'true')
User.create!(name: 'George Ruth', nickname: 'The Babe', email: 'gruth@brandeis.edu', password: '12345678')
User.create!(name: 'Joe Dimaggio', nickname: 'Joltin Joe', email: 'jdimmagio@brandeis.edu', password: '12345678')
User.create!(name: 'Gary Carter', nickname: 'Kid', email: 'gcarter@brandeis.edu', password: '12345678')
User.create!(name: 'Sean Casey', nickname: 'The Mayor', email: 'scasey@brandeis.edu', password: '12345678')
User.create!(name: 'Lou Gehrig', nickname: 'Buster', email: 'lgehrig@brandeis.edu', password: '12345678')
User.create!(name: 'Ken Griffey', nickname: 'The Natural', email: 'kgriffey@brandeis.edu', password: '12345678')
User.create!(name: 'Roy Halladay', nickname: 'Doc', email: 'rhalladay@brandeis.edu', password: '12345678')
User.create!(name: 'Mike Hargrove', nickname: 'The Human Rain Delay', email: 'mhargrove@brandeis.edu', password: '12345678')
User.create!(name: 'Orel Hershiser', nickname: 'Bulldog', email: 'ohershiser@brandeis.edu', password: '12345678')
User.create!(name: 'Reggie Jackson', nickname: 'Mr. October', email: 'rjackson@brandeis.edu', password: '12345678')
User.create!(name: 'Randy Johnson', nickname: 'Big Unit', email: 'rjohnson@brandeis.edu', password: '12345678')
User.create!(name: 'Thurman Munson', nickname: 'Tugboat', email: 'tmunson@brandeis.edu', password: '12345678')
User.create!(name: 'Phil Rizzuto', nickname: 'Scooter', email: 'prizzuto@brandeis.edu', password: '12345678')
User.create!(name: 'Willie Stargell', nickname: 'Pops', email: 'wstargell@brandeis.edu', password: '12345678')


Group.create(name: 'Group 1')
Group.create(name: 'Group 2')

Assignment.create(title: 'Baseball', description: 'What do you know about baseball?', due: '2015-09-02 12:00:00 UTC')
Assignment.create(title: 'Nickname', description: 'Why did you choose your nickname?', due: '2015-09-02 12:00:00 UTC')

Post.create(user_id: 2, assignment_id: 1, user_name: 'George Ruth', user_nickname: 'The Babe', title: 'Power Hitting', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 3, assignment_id: 1, user_name: 'Joe Dimaggio', user_nickname: 'Joltin Joe', title: 'Streaks', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 4, assignment_id: 1, user_name: 'Gary Carter', user_nickname: 'Kid', title: 'Toronto Eateries', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 5, assignment_id: 1, user_name: 'Sean Casey', user_nickname: 'The Mayor', title: 'Singles', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 6, assignment_id: 1, user_name: 'Lou Gehrig', user_nickname: 'Buster', title: 'Luck', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 7, assignment_id: 1, user_name: 'Ken Griffey', user_nickname: 'The Natural', title: 'Line Drives', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 8, assignment_id: 1, user_name: 'Roy Halladay', user_nickname: 'Doc', title: 'Three-quarters', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 9, assignment_id: 1, user_name: 'Mike Hargrove', user_nickname: 'The Human Rain Delay', title: 'Preparation', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 10, assignment_id: 1, user_name: 'Orel Hershiser', user_nickname: 'Bulldog', title: 'Control', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 11, assignment_id: 1, user_name: 'Reggie Jackson', user_nickname: 'Mr. October', title: 'Halloween', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 12, assignment_id: 1, user_name: 'Randy Johnson', user_nickname: 'Big Unit', title: 'Altitude and Attitude', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 13, assignment_id: 1, user_name: 'Thurman Munson', user_nickname: 'Tugboat', title: 'MVP', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 14, assignment_id: 1, user_name: 'Phil Rizzuto', user_nickname: 'Scooter', title: 'Bunting', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')
Post.create(user_id: 15, assignment_id: 1, user_name: 'Willie Stargell', user_nickname: 'Pops', title: 'Upper Deck', content: 'Lorem ipsum dolor sit amet, magna purus sed eleifend nibh imperdiet. Nascetur ante et quis adipiscing libero augue, mollis nec dictum pede, cursus mauris laoreet nam. Id lacinia justo a tellus, ut venenatis phasellus commodo gravida sapien, porta metus nec rutrum maecenas. Nam et sit, vitae vehicula lacus ipsum ac arcu elementum, cras lectus nulla non ut vulputate, vero tristique mauris, sed eu vitae ut vivamus. Praesent nullam sed neque praesent at urna, risus fringilla malesuada egestas. Fermentum ac et, purus amet, nunc felis vehicula sed venenatis incidunt ipsum, ac dictum vitae nostra nulla porta enim, leo risus dictum accumsan elementum.')

Notification.create(message: 'Go to class!', user_notified: '0')
Notification.create(message: 'Notification to G Ruth 1', link: '', user_notified: '3')
Notification.create(message: 'Notification to G Ruth 2', user_notified: '3')
Notification.create(message: 'Notification to G Ruth 3', user_notified: '3')
Notification.create(message: 'Notification to Joe Dimaggio 1', link: '', user_notified: '4')
Notification.create(message: 'Notification to Joe Dimaggio 2', link: '', user_notified: '4')
Notification.create(message: 'Notification to Joe Dimaggio 3', link: '', user_notified: '4')

@users = User.where(admin: nil)
@users.each do |u|
	@groups = Group.all
    @group = @groups.sample
    @group.users << u
end